[package]
name = "nestle_ines"
version = "0.1.0"
authors = ["Zeyi Fan <github@zeyi.fan>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
thiserror = "1.0.20"
binread = "1.0.2"
