[package]
name = "asm6502"
version = "0.1.0"
authors = ["Zeyi Fan <github@zeyi.fan>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asm6502_derive = { path = "../asm6502_derive" }
enum_dispatch = "0.3.2"
