[package]
name = "nestle_cpu"
version = "0.1.0"
authors = ["Zeyi Fan <github@zeyi.fan>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
