[package]
name = "asm6502_derive"
version = "0.1.0"
authors = ["Zeyi Fan <github@zeyi.fan>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.7"
syn = "1.0.36"
darling = "0.10.2"
proc-macro2 = "1.0.19"